development:
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  secret_key_base: fa6da54a73e9675fe3ce19c98b99ab4695b3f681532214389276f05b30226dbcb94c0d1b0611b5b230576f7e56a0e4219eb4edd1781eac268d2b545d1d3a5626

test:
  secret_key_base: c9417ade5cb1cf7088a58ec262de52638716264f5f3fc059ea007442daa018df7325742a1c65fa8737035d318535a6e0d9ce49a8c5c1a13d9f1ac746acb08880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

